name: premium

on:
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start VPS Session
(tmate)
        uses: mxschmitt/action
-tmate@v3
        with:
        
limit-access-to-actor: false
